basic_args:
  output_dir: ./output/
  overwrite_output_dir: True
  seed: 42
  n_gpu: 1
  n_nodes: 1
  distributed_accelerator: null
  do_train: False
  do_eval: False
  do_test: True

data_args:
  dataset_name: tobacco3842
  dataset_dir: ./data/Tobacco3482
  data_caching_args:
    use_datadings: False
    cache_resized_images: True
    cache_image_size: [224, 224]
    load_data_to_ram: False
    cached_data_name: '-'
    dataset_cache_dir: ./tmp/cache
  data_splitting_args:
    train_val_sampling_strategy: random_split
    random_split_ratio: 0.8
    # k_folds: 5
  train_aug_args:
    - name: basic_image
      keys:
        - image
      params:
          - gray_to_rgb: True
            rescale_strategy: rescale_simple
            rescale_params:
              rescale_dim: 224
              rescale_both_dims: True
            normalize: True
  eval_aug_args:
    - name: basic_image
      keys:
        - image
      params:
        - gray_to_rgb: True
          rescale_strategy: rescale_simple
          rescale_params:
            rescale_dim: 224
            rescale_both_dims: True
          normalize: True
  data_loader_args:
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    dataloader_drop_last: False
    shuffle_data: True
    pin_memory: True
    dataloader_num_workers: 1
    # max_train_samples: 100
    # max_val_samples: 100
    # max_test_samples: 100
    # aspect_ratio_grouping_factor: -1
  data_tokenization_args:
    tokenize_dataset: False
    # tokenizer_name: basic_english
    # tokenizer_lib: torchtext
    # pad_to_max_length: True
    # # label_all_tokens: False
  extras: null

model_args:
  model_name: docxclassifier
  model_type: _base
  model_task: image_classification
  model_version: tobacco_imagenet_ft
  cache_dir: ${NETSCRATCH_DAS}/pretrained/
  use_return_dict: True
  model_checkpoint_file: https://cloud.dfki.de/owncloud/index.php/s/m2XR3yL3TFKesCx/download/base_tobacco_imagenet.pth